language: go
sudo: false

go:
        - 1.4
        - 1.5
        - 1.6
        - 1.7
        - 1.8
        - 1.9
        - 1.10
        - tip

script:
        - go build
        - if [ $(./gover ./gover | cut -d\  -f 1) != $(go version | cut -d\  -f 3) ]; then exit 1; fi
        - if [ $(./gover $(which go) | cut -d\  -f 1) != $(go version | cut -d\  -f 3) ]; then exit 1; fi
